all: LocalLib

LocalLib: 
	cd Globals; make;
	cd Inputs; make;
	cd GalaxyCompCombine; make;
	cd GalaxyMove; make;
	cd Outputs; make;
	cd Main; make;



clean:
	cd Globals; make clean;
	cd Inputs; make clean;
	cd GalaxyCompCombine; make clean;
	cd GalaxyMove; make clean;
	cd Outputs; make clean;
	cd Main; make clean;
	

