all: LocalLib

LocalLib: 
	cd GeneralMath; make;
	cd RandomNumbers; make;
	cd Objects; make;
	cd Sort; make;
	cd CoordinateTransforms; make;
	cd CenterOfMass; make;
	cd GalaxyIOs; make
	cd GalComponentMath; make	
	cd GalAdjustments; make;



clean:
	cd Objects; make clean;
	cd RandomNumbers; make clean;
	cd GeneralMath; make clean;
	cd Sort; make clean;
	cd CoordinateTransforms; make clean;
	cd CenterOfMass; make clean
	cd GalaxyIOs; make clean;
	cd GalComponentMath; make clean
	cd GalAdjustments; make clean

