cccccccccccccccccccccccccccccccccccccccccccccccccccc
c     
c     This module reads in the mass and truncation radii file generated by
c       dbh
ccccccccccccccccccccccccccccccccccccccccccccccccccc

      module ReadMRMod
      use GenCompGlobs

      implicit none

      contains

      subroutine readmassrad()
      implicit none

      open(10,file='mr.dat',status='old')
      read(10,*) diskmass,diskedge
      read(10,*) bulgemass,bulgeedge
      read(10,*) halomass,haloedge
      close(10)

      end subroutine


      end module

