cccccccccccccccccccccccccccccccccccccccccccccccccccc
c     
c     This module reads in the harmonics file generated by
c       dbh
ccccccccccccccccccccccccccccccccccccccccccccccccccc

      module ReadDiskDFMod
      use Globs
      use GenCompGlobs
      use iniDBHMod
      use DiskObjDef

      implicit none

      contains

cccccc
      subroutine readdiskdf()
      implicit none

      character(30) CorFile
      integer i

      print*, "read disk df"
      if(DiskSwitch .eq. 1) then
        DUse=D1
        CorFile='cordbh.dat'
      elseif(DiskSwitch .eq. 2) then
        DUse=D2
        CorFile='cordbh2.dat'
      endif

      open(17,file=CorFile,status='old')
c      read(17,'(2x, 2g17.7,1x,i4,2g17.7)') DUse%sigr0,DUse%disksr,DUse%nrspl
c     &              , DUse%sig_n
      read(17,'(2x, 2g17.7,1x,i4,2g17.7)') DUse%sigr01,DUse%disksr1
     &                 ,DUse%nrspl
     &              , DUse%sigr02,DUse%disksr2
      print*, "Reading diskdf cordbh file",DUse%nrspl
      call DiskDFALLOCATE(DUse)
      do i=0,DUse%nrspl
        read(17,*) DUse%rr(i),DUse%fdrat(i),DUse%fszrat(i)
      enddo
      close(17)


      return
      end subroutine
ccccccc



      end module

