cccccccccccccccccccccccccccccccccccccccccccccccccccc
c     
c     This module reads in the harmonics file generated by
c       dbh
ccccccccccccccccccccccccccccccccccccccccccccccccccc

      module ReadDensPsiMod
      use Globs
      use iniDBHMod

      implicit none

      contains


ccccc
      subroutine ReadDensPsiBulge()
      implicit none
      integer i

      open(file='denspsibulge.dat',unit=50,status='old')

      do i=1,npsi
        read(50,*) DF%tableE(i),DF%denspsibulge(i)
      enddo
      close(50)

      open(file='dfsersic.dat',unit=50,status='old')

      do i=1,npsi
        read(50,*) DF%tableE(i),DF%dfsersic(i)
      enddo
      close(50)

      return
      end subroutine
ccccccc

ccccc
      subroutine ReadDensPsiHalo()
      implicit none
      integer i

c      print*, "Read Dens Psi Halo", npsi, shape(DF%tableE)
      open(file='denspsihalo.dat',unit=50,status='old')

      do i=1,npsi
        read(50,*) DF%tableE(i),DF%denspsihalo(i)
      enddo
      close(50)

      open(file='dfnfw.dat',unit=50,status='old')

      do i=1,npsi
        read(50,*) DF%tableE(i),DF%dfnfw(i)
      enddo
      close(50)

      return
      end subroutine
ccccccc

      end module

