cccccccccccccccccccccccccccccccccccccccccccccccccccc
c     
c     This module reads in the harmonics file generated by
c       dbh
ccccccccccccccccccccccccccccccccccccccccccccccccccc

      module ReadZGasGridMod
      use GasObjDef

      implicit none

      contains


ccccc
      subroutine ReadZGasGrid(fname,G)
      implicit none
      integer ir
      character(*) fname
      Type(GasObj) G

      print*, "Read ZGas Grid ", fname,G%nr,shape(G%rgasgrid)
      open(10,file=trim(fname),status='old')
      do ir=0,G%nr
        read(10,*) G%rgasgrid(ir),G%zgasgrid(ir)
      enddo
      close(10)
      return
      end subroutine

      end module

